# feeder
feeder: st_gcn.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTU-RGB-D_zero_shot/xview/train_data.npy
  label_path: ./data/NTU-RGB-D_zero_shot/xview/train_label.pkl
test_feeder_args:
  data_path: ./data/NTU-RGB-D_zero_shot/xview/val_data.npy
  label_path: ./data/NTU-RGB-D_zero_shot/xview/val_label.pkl


# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 60
  channel: 3
  window_size: 300
  num_point: 25
  num_person: 2
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True 

# test 
phase: test
device: 0
batch_size: 48 
test_batch_size: 48
# weights: ./model/ntuxview-st_gcn_zero_shot.pt
weights: ./work_dir/NTU-RGB-D_zero_shot/xview/ST_GCN/epoch31_model.pt


